POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer <token>

{
    "title": "PUT vs POST: What's the difference?",
    "author": "Cameron McKenzie",
    "url": "https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/PUT-vs-POST-Whats-the-difference",
    "userId": "648f2db02d64d330c182fe00",
    "likes": 12,
    "comments": []
}